DirtX.Web/Controllers/GearController.cs
using DirtX.Core.Enums;
using DirtX.Core.Interfaces;
using DirtX.Core.Models;
using DirtX.Infrastructure.Data.Models.Enums;
using DirtX.Infrastructure.Data.Models.Mappings;
using DirtX.Infrastructure.Data.Models.Products;
using Microsoft.AspNetCore.Mvc;

namespace DirtX.Web.Controllers
{
    public class GearController : BaseController
    {
        private readonly IProductService productService;

        public GearController(ILogger<GearController> _logger, IProductService _productService)
        {
            productService = _productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Product> gears = await productService.GetAllGearsAsync();
                List<ProductBrand> gearBrands = await productService.GetDistinctProductBrandsAsync(gears);
                List<ProductCategory> gearTypes = productService.GetProductCategories(gears);

                if (gears is null || gearBrands is null || gearTypes is null)
                {
                    return NotFound();
                }

                List<ProductIndexViewModel> model = gearTypes.Select(types =>
                {
                    return new ProductIndexViewModel
                    {
                        ProductCategory = types.ToString(),
                        Brands = gearBrands
                    };
                }).ToList();

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Category(string category, ProductSorting sorting = ProductSorting.Name_Ascending)
        {
            try
            {
                if (Enum.TryParse(category, out ProductCategory currCategory))
                {
                    List<Product> gears = await productService.GetAllProductsByCategoryAsync(currCategory, sorting);

                    if (gears is null)
                    {
                        return NotFound();
                    }

                    ProductCategoryViewModel model = new()
                    {
                        ProductCategory = category.ToString(),
                        Products = gears
                    };

                    return View(model);
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Brand(string brandName)
        {
            try
            {
                ProductBrand brand = await productService.GetProductBrandAsync(brandName);

                if (brand is null)
                {
                    return NotFound();
                }

                List<Product> gears = await productService.GetProductsByBrandAsync(brand);

                if (gears is null)
                {
                    return NotFound();
                }

                ProductBrandViewModel model = new()
                {
                    Name = brand.Name,
                    Description = brand.Description,
                    ImageUrl = brand.ImageUrl,
                    Products = gears
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                Product gear = await productService.GetProductAsync(id);

                if (gear is null)
                {
                    return NotFound();
                }

                List<ProductSpecification> gearSpecs = await productService.GetProductSpecificationsAsync(id);

                ProductDetailsViewModel model = new()
                {
                    Id = gear.Id,
                    BrandName = gear.Brand.Name,
                    Title = gear.Title,
                    Price = gear.Price,
                    Description = gear.Description,
                    ImageUrl = gear.ImageUrl,
                    StockQuantity = gear.StockQuantity,
                    Specs = gearSpecs
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }
    }
}

DirtX.Web/Controllers/OilController.cs
using DirtX.Core.Enums;
using DirtX.Core.Interfaces;
using DirtX.Core.Models;
using DirtX.Infrastructure.Data.Models.Enums;
using DirtX.Infrastructure.Data.Models.Mappings;
using DirtX.Infrastructure.Data.Models.Products;
using Microsoft.AspNetCore.Mvc;

namespace DirtX.Web.Controllers
{
    public class OilController : BaseController
    {
        private readonly IProductService productService;

        public OilController(IProductService _productService)
        {
            productService = _productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Product> oils = await productService.GetAllOilsAsync();
                List<ProductBrand> oilBrands = await productService.GetDistinctProductBrandsAsync(oils);
                List<ProductCategory> oilTypes = productService.GetProductCategories(oils);

                if (oils is null || oilBrands is null || oilTypes is null)
                {
                    return NotFound();
                }

                List<ProductIndexViewModel> model = oilTypes.Select(types =>
                {
                    return new ProductIndexViewModel
                    {
                        ProductCategory = types.ToString(),
                        Brands = oilBrands
                    };
                }).ToList();

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Category(string category, ProductSorting sorting = ProductSorting.Name_Ascending)
        {
            try
            {
                if (Enum.TryParse(category, out ProductCategory currCategory))
                {
                    List<Product> oils = await productService.GetAllProductsByCategoryAsync(currCategory, sorting);

                    if (oils is null)
                    {
                        return NotFound();
                    }

                    ProductCategoryViewModel model = new()
                    {
                        ProductCategory = category.ToString(),
                        Products = oils
                    };

                    return View(model);
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Brand(string brandName)
        {
            try
            {
                ProductBrand brand = await productService.GetProductBrandAsync(brandName);

                if (brand is null)
                {
                    return NotFound();
                }

                List<Product> oils = await productService.GetProductsByBrandAsync(brand);

                if (oils is null)
                {
                    return NotFound();
                }

                ProductBrandViewModel model = new()
                {
                    Name = brand.Name,
                    Description = brand.Description,
                    ImageUrl = brand.ImageUrl,
                    Products = oils
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                Product oil = await productService.GetProductAsync(id);

                if (oil is null)
                {
                    return NotFound();
                }

                List<ProductSpecification> oilSpecs = await productService.GetProductSpecificationsAsync(id);

                ProductDetailsViewModel model = new()
                {
                    Id = oil.Id,
                    BrandName = oil.Brand.Name,
                    Title = oil.Title,
                    Price = oil.Price,
                    Description = oil.Description,
                    ImageUrl = oil.ImageUrl,
                    StockQuantity = oil.StockQuantity,
                    Specs = oilSpecs
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }
    }
}

DirtX.Web/Controllers/PartController.cs
using DirtX.Core.Enums;
using DirtX.Core.Interfaces;
using DirtX.Core.Models;
using DirtX.Infrastructure.Data.Models;
using DirtX.Infrastructure.Data.Models.Enums;
using DirtX.Infrastructure.Data.Models.Mappings;
using DirtX.Infrastructure.Data.Models.Motorcycles;
using DirtX.Infrastructure.Data.Models.Products;
using Microsoft.AspNetCore.Mvc;

namespace DirtX.Web.Controllers
{
    public class PartController : BaseController
    {
        private readonly IProductService productService;

        public PartController(IProductService _productService)
        {
            productService = _productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Product> parts = await productService.GetAllPartsAsync();
                List<ProductBrand> partBrands = await productService.GetDistinctProductBrandsAsync(parts);
                List<ProductCategory> partTypes = productService.GetProductCategories(parts);

                if (parts is null || partBrands is null || partTypes is null)
                {
                    return NotFound();
                }

                List<ProductIndexViewModel> model = partTypes.Select(types =>
                {
                    return new ProductIndexViewModel
                    {
                        ProductCategory = types.ToString(),
                        Brands = partBrands
                    };
                }).ToList();

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Category(string category, ProductSorting sorting = ProductSorting.Name_Ascending)
        {
            try
            {
                if (Enum.TryParse(category, out ProductCategory currCategory))
                {
                    List<Product> parts = await productService.GetAllProductsByCategoryAsync(currCategory, sorting);

                    if (parts is null)
                    {
                        return NotFound();
                    }

                    ProductCategoryViewModel model = new()
                    {
                        ProductCategory = category.ToString(),
                        Products = parts
                    };

                    return View(model);
                }
                else
                {
                    return RedirectToAction(nameof(Error));
                }
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Brand(string brandName)
        {
            try
            {
                ProductBrand brand = await productService.GetProductBrandAsync(brandName);

                if (brand is null)
                {
                    return NotFound();
                }

                List<Product> parts = await productService.GetProductsByBrandAsync(brand);

                if (parts is null)
                {
                    return NotFound();
                }

                ProductBrandViewModel model = new()
                {
                    Name = brand.Name,
                    Description = brand.Description,
                    ImageUrl = brand.ImageUrl,
                    Products = parts
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                Product part = await productService.GetProductAsync(id);

                if (part is null)
                {
                    return NotFound();
                }

                List<ProductSpecification> partSpecs = await productService.GetProductSpecificationsAsync(id);

                ProductDetailsViewModel model = new()
                {
                    Id = part.Id,
                    BrandName = part.Brand.Name,
                    Title = part.Title,
                    Price = part.Price,
                    Description = part.Description,
                    ImageUrl = part.ImageUrl,
                    StockQuantity = part.StockQuantity,
                    Specs = partSpecs
                };

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error));
            }
        }

        [HttpGet]
        public async Task<IActionResult> CompatibleParts(int makeId, int modelId, int displacementId, int yearId)
        {
            try
            {
                List<MotorcycleProduct> compatibleParts = await productService.GetCompatiblePartsAsync(makeId, modelId, displacementId, yearId);

                if (compatibleParts is null)
                {
                    return BadRequest();
                }

                Motorcycle motorcycle = compatibleParts.FirstOrDefault().Motorcycle;

                if (motorcycle is null)
                {
                    return NotFound();
                }

                CompatiblePartsViewModel model = new()
                {
                    Make = motorcycle.Make.Title,
                    Model = motorcycle.Model.Title,
                    Displacement = motorcycle.Displacement.Volume.ToString(),
                    Year = motorcycle.Year.ManufactureYear.ToString(),
                    Parts = compatibleParts.Select(cp => cp.Product).ToList(),
                };

                return View(model);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

DirtX.Web/Views/Shared/Error400.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Error 400 - Bad Request</title>
    <link rel="stylesheet" href="~/css/error400.css" />
</head>
<body>
    <h1>Uh-oh! Bad Request</h1>
    <p>It seems the server couldn't understand your request.</p>
    <br />
    <p><a href="/">Go Back to Homepage</a></p>
</body>
</html>

DirtX.Web/Views/Shared/Error404.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Error 404 - Not Found</title>
    <link rel="stylesheet" href="~/css/error404.css" />
</head>
<body>
    <h1>Oops! Looks like you took a wrong turn!</h1>
    <br/>
    <ul class="redirect-from-error">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Part">Parts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Oil">Oils and Liquids</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Gear">Riding Gear</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Used">Used Motorcycles</a>
        </li>
    </ul>
</body>
</html>

DirtX.Web/Views/Shared/Error500.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Error 500 - Internal Server Error</title>
    <link rel="stylesheet" href="~/css/error500.css" />
</head>
<body>
    <h1>Oops! Something Went Wrong</h1>
    <p>We're sorry, but there was a problem processing your request.</p>
    <p>Our team has been notified and is working to fix it. Please try again later.</p>
    <br/>
    <p><a href="/">HOMEPAGE</a></p>
</body>
</html>

DirtX.Web/Views/Shared/_AllBrandProducts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DirtX.Web/Views/Shared/_BrandCategoryPartial.cshtml
@model ProductCategoryViewModel

<div class="products-container">
    @foreach (var product in Model.Products)
    {
        <div class="product">
            <h2>@product.Title</h2>
            <p>@product.Description</p>
            <p>Price: @product.Price</p>

            @if (product.TypeId == 1)
            {
                <a href="@Url.Action("Details", "Part", new { id = product.Id })">View Details</a>
            }
            else if (product.TypeId == 2)
            {
                <a href="@Url.Action("Details", "Oil", new { id = product.Id })">View Details</a>
            }
            else if (product.TypeId == 3)
            {
                <a href="@Url.Action("Details", "Gear", new { id = product.Id })">View Details</a>
            }
        </div>
    }
</div>

DirtX.Web/Views/Shared/_BrandDetailsPartial.cshtml
@model ProductBrandViewModel

<div class="brand-container">
    <div class="brand-image">
        <img src="@Model.ImageUrl" alt="@Model.Name" style="width: 150px; height: 150px; border: solid 1px black" />
    </div>
    <div class="brand-details">
        <h4>@Model.Name</h4>
        <p>@Model.Description</p>
    </div>
</div>

<hr />

DirtX.Web/Views/Shared/_BrandProductsPartial.cshtml
@model ProductBrandViewModel

<div class="products-container">
    @foreach (var product in Model.Products)
    {
        <div class="product">
            <div class="image-container">
                <img src="@product.ImageUrl" alt="@product.Title" class="product-image">
            </div>
            <div class="product-details">
                <h2>@product.Title</h2>
                <p>@product.Description</p>
                <p class="price">Price: @product.Price BGN</p>

                @if (product.TypeId == 1)
                {
                    <a href="@Url.Action("Details", "Part", new { id = product.Id })">View Details</a>
                }
                else if (product.TypeId == 2)
                {
                    <a href="@Url.Action("Details", "Oil", new { id = product.Id })">View Details</a>
                }
                else if (product.TypeId == 3)
                {
                    <a href="@Url.Action("Details", "Gear", new { id = product.Id })">View Details</a>
                }
            </div>
        </div>
    }
</div>

DirtX.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]DirtX</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DirtX.Web.styles.css" asp-append-version="true" />
</head>
<body>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Part" asp-action="Index">Parts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Oil" asp-action="Index">Oils and Liquids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gear" asp-action="Index">Riding Gear</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Used" asp-action="Index">Used Motorcycles</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer-container">
            &copy; @DateTime.Today.Year - DirtX.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Html.PartialAsync("_ValidationScriptsPartial")
</body>
</html>

DirtX.Web/Views/Shared/_ProductCategoryPartial.cshtml
@model ProductCategoryViewModel

<div class="products-container">
    @foreach (var product in Model.Products)
    {
        <a href="@GetProductDetailsUrl(product)" class="product-cell @(product.StockQuantity == 0 ? "out-of-stock" : "")">
            <div class="product-image">
                <img src="@product.ImageUrl" alt="@product.Title">
                @if (product.StockQuantity == 0)
                {
                    <div class="out-of-stock-overlay">Out of Stock</div>
                }
            </div>
            <div class="product-details">
                <h2>@product.Title</h2>
                <p>@product.Description</p>
            </div>
            <div class="product-actions">
                <p>Price: @product.Price BGN</p>
            </div>
        </a>
    }
</div>

@functions {
    public string GetProductDetailsUrl(Product product)
    {
        switch (product.TypeId)
        {
            case 1:
                return Url.Action("Details", "Part", new { id = product.Id });
            case 2:
                return Url.Action("Details", "Oil", new { id = product.Id });
            case 3:
                return Url.Action("Details", "Gear", new { id = product.Id });
            default:
                return "#";
        }
    }
}

DirtX.Web/Views/Shared/_ProductDetailsPartial.cshtml
@model ProductDetailsViewModel

@{
    bool isAuthenticated = User.Identity.IsAuthenticated;
}

<div class="custom-container">
    <h3 class="custom-heading">PRODUCT'S DETAILS</h3>
    <div class="product-details">
        <div class="image-container">
            <img src="@Model.ImageUrl" alt="Product Image" class="custom-img" />
        </div>
        <div class="details-container">
            <div class="brand-title-container">
                <h4 class="custom-title">@Model.BrandName - @Model.Title</h4>
            </div>
            <div class="description-container">
                <p class="custom-title">@Model.Description</p>
            </div>
            @if (Model.Specs.Any())
            {
                <div class="custom-specs">
                    <h4 class="custom-title">Specifications:</h4>
                    @foreach (var spec in Model.Specs)
                    {
                        <div class="custom-spec">
                            <p><strong>@spec.Specification.Title:</strong> @spec.Specification.Value</p>
                        </div>
                    }
                </div>
            }
            @if (@Model.StockQuantity > 0)
            {
                @if (isAuthenticated)
                {
                    <form asp-controller="Cart" asp-action="Add" asp-route-id="@Model.Id" method="post" class="mb-2">
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                    </form>
                }
                else
                {
                    <form action="@Url.Action("Login", "User")" method="get" class="mb-2">
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                        <input type="hidden" name="productId" value="@Model.Id" />
                    </form>
                }
            }
            else
            {
                <div class="alert alert-warning" role="alert">
                    Product is Out of Stock!
                </div>
            }
            <div class="price-container">
                <div class="custom-price">
                    Price: @Model.Price BGN
                </div>
            </div>
        </div>
    </div>
</div>

DirtX.Web/Views/Shared/_ProductListPartial.cshtml
@model ProductBrandViewModel

<div class="products-container">
    @foreach (var product in Model.Products)
    {
        <div class="product">
            <h2>@product.Title</h2>
            <p>@product.Description</p>
            <p>Price: @product.Price</p>

            @if (product.TypeId == 1)
            {
                <a href="@Url.Action("Details", "Part", new { id = product.Id })">View Details</a>
            }
            else if (product.TypeId == 2)
            {
                <a href="@Url.Action("Details", "Oil", new { id = product.Id })">View Details</a>
            }
            else if (product.TypeId == 3)
            {
                <a href="@Url.Action("Details", "Gear", new { id = product.Id })">View Details</a>
            }
        </div>
    }
</div>

DirtX.Web/Views/Shared/_ProductSortingPartial.cshtml
<div style="display: flex; align-items: center;">
    <h1>@Model.ProductCategory.Replace("_", " ")</h1>

    <form method="get" asp-action="Category" style="margin-left: auto;">
        <input type="hidden" name="category" value="@Model.ProductCategory" />
        <select name="sorting">
            <option value="Name_Ascending">Name (A-Z)</option>
            <option value="Name_Descending">Name (Z-A)</option>
            <option value="Price_Ascending">Price (Low to High)</option>
            <option value="Price_Descending">Price (High to Low)</option>
        </select>
        <button type="submit">Sort</button>
    </form>
</div>